/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_muni_fi_model_Model */

#ifndef _Included_cz_muni_fi_model_Model
#define _Included_cz_muni_fi_model_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_muni_fi_model_Model
 * Method:    cppLoad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cz_muni_fi_model_Model_cppLoad
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
