/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_muni_fi_distributed_graph_NodeFactory */

#ifndef _Included_cz_muni_fi_distributed_graph_NodeFactory
#define _Included_cz_muni_fi_distributed_graph_NodeFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_muni_fi_distributed_graph_NodeFactory
 * Method:    getNativePredecessors
 * Signature: ([ILcz/muni/fi/model/ColorSet;Ljava/util/Map;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_cz_muni_fi_distributed_graph_NodeFactory_getNativePredecessors
  (JNIEnv *, jobject, jintArray, jobject, jobject);

/*
 * Class:     cz_muni_fi_distributed_graph_NodeFactory
 * Method:    getNativeSuccessors
 * Signature: ([ILcz/muni/fi/model/ColorSet;Ljava/util/Map;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_cz_muni_fi_distributed_graph_NodeFactory_getNativeSuccessors
  (JNIEnv *, jobject, jintArray, jobject, jobject);

/*
 * Class:     cz_muni_fi_distributed_graph_NodeFactory
 * Method:    getNativeInit
 * Signature: (Ljava/lang/String;IFLjava/util/List;Ljava/util/Map;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_cz_muni_fi_distributed_graph_NodeFactory_getNativeInit
  (JNIEnv *, jobject, jstring, jint, jfloat, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
