/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_muni_fi_thomas_NetworkModel */

#ifndef _Included_cz_muni_fi_thomas_NetworkModel
#define _Included_cz_muni_fi_thomas_NetworkModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_muni_fi_thomas_NetworkModel
 * Method:    loadNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cz_muni_fi_thomas_NetworkModel_loadNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
