/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_muni_fi_thomas_NativeModel */

#ifndef _Included_cz_muni_fi_thomas_NativeModel
#define _Included_cz_muni_fi_thomas_NativeModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_muni_fi_thomas_NativeModel
 * Method:    loadNative
 * Signature: (Ljava/lang/String;Lcz/muni/fi/thomas/NetworkModel;)V
 */
JNIEXPORT void JNICALL Java_cz_muni_fi_thomas_NativeModel_loadNative
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
