/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_muni_fi_ode_NodeFactory */

#ifndef _Included_cz_muni_fi_ode_NodeFactory
#define _Included_cz_muni_fi_ode_NodeFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
